---
title: "Model Comparisons- American Novels"
author: "Jessica Young"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\section{Novel Pairs Regression Analysis}

```{r, echo=FALSE, message=F}
load("C:/Users/jyoung22.ADND/Documents/Network Analysis/Amer_Novels_Env.RData")
source("C:/Users/jyoung22.ADND/Documents/Network Analysis/regplot.R")
library(caret)
library(rminer)
library(stringr)
library(dplyr)
library(reshape2)
library(foreach)
library(doParallel)
library(parallel)
library(ggplot2)
library(car)
```
```{r,eval=F,echo=F}
amer_novels = read.csv("C:/Users/jyoung22.ADND/Documents/Network Analysis/REVIEWS_PAIRS_ALLDATA.csv")
amer_novels$connected = ifelse(amer_novels$connections_books>0,1,0)

amer_novels$BothBlack = ifelse(amer_novels$BLACK1==1 & amer_novels$BLACK2==1,1,0)
amer_novels$BothWhite = ifelse(amer_novels$WHITE1==1 & amer_novels$WHITE2==1,1,0)
amer_novels$BothPOC = ifelse(amer_novels$POC1==1  &amer_novels$POC2==1,1,0)

amer_novels$BothMale = ifelse(amer_novels$Male1==1 &amer_novels$Male2==1,1,0)
amer_novels$BothFemale = ifelse(amer_novels$Female1==1&amer_novels$Female2==1,1,0)

amer_novels$P_0_Match = ifelse(amer_novels$PUB2_0_1==1&amer_novels$PUB2_0_2==1,1,0)
amer_novels$P_1_Match = ifelse(amer_novels$PUB2_1_1==1&amer_novels$PUB2_1_2==1,1,0)
amer_novels$P_2_Match = ifelse(amer_novels$PUB2_2_1==1&amer_novels$PUB2_2_2==1,1,0)
amer_novels$P_3_Match = ifelse(amer_novels$PUB2_3_1==1&amer_novels$PUB2_3_2==1,1,0)
amer_novels$P_4_Match = ifelse(amer_novels$PUB2_4_1==1&amer_novels$PUB2_4_2==1,1,0)
amer_novels$P_5_Match = ifelse(amer_novels$PUB2_5_1==1&amer_novels$PUB2_5_2==1,1,0)
amer_novels$P_6_Match = ifelse(amer_novels$PUB2_6_1==1&amer_novels$PUB2_6_2==1,1,0)
amer_novels$P_7_Match = ifelse(amer_novels$PUB2_7_1==1&amer_novels$PUB2_7_2==1,1,0)
amer_novels$P_8_Match = ifelse(amer_novels$PUB2_8_1==1&amer_novels$PUB2_8_2==1,1,0)
amer_novels$P_9_Match = ifelse(amer_novels$PUB2_9_1==1&amer_novels$PUB2_9_2==1,1,0)
amer_novels$P_10_Match = ifelse(amer_novels$PUB2_10_1==1&amer_novels$PUB2_10_2==1,1,0)


amer_novels$RaceMatch = ifelse(amer_novels$BothBlack==1 |amer_novels$BothWhite==1 | amer_novels$BothPOC==1,1,0)
amer_novels$GenderMatch = ifelse(amer_novels$BothMale==1 |amer_novels$BothFemale==1,1,0)

amer_novels$MatchingRaces = factor(ifelse(amer_novels$BLACK1==1 & amer_novels$BLACK2==1,'Black',
                                   ifelse(amer_novels$WHITE1==1 & amer_novels$WHITE2==1, 'White',
                                          ifelse(amer_novels$POC1==1  &amer_novels$POC2==1,'POC','NoMatch'))))

amer_novels$MatchingRaces = factor(amer_novels$MatchingRaces, levels(amer_novels$MatchingRaces)[c(2,1,3,4)])


amer_novels = na.omit(amer_novels)

```
```{r, echo=F}
library(corrplot)
corrplot(cor(amer_novels[,c('BothBlack' , 'BothWhite' , 'BothPOC' , 'BothMale' , 'BothFemale' ,
        'ACAD_Match' , 'BLACK_Match' , 'ELITE_Match' , 'GENRE_Match' , 'LIT_Match' , 'MAIN_Match' , 'MISC_Match' , 'TRADE_Match' , 'nan_Match' , 
        'P_0_Match' , 'P_1_Match' , 'P_2_Match' , 'P_3_Match' , 'P_4_Match' , 'P_5_Match' , 'P_6_Match' , 'P_7_Match' , 'P_8_Match' , 'P_9_Match' ,'P_10_Match')]))

    
ggplot(amer_novels, aes(x=connections_books))+geom_density()
```


Model for 1965-1970

```{r, eval=F}
a_1 = amer_novels %>%
      filter(Years=="65-70")
  
ggplot(a_1, aes(x=connections_books))+geom_density()

            log_model1 = train(connections_books~ BothBlack + BothWhite + BothPOC + BothMale + BothFemale +
                                  BothBlack:BothMale + BothBlack:BothFemale + 
                                  BothWhite:BothMale + BothWhite:BothFemale +
                                  BothPOC:BothMale + BothPOC:BothFemale +
                                  ACAD_Match + BLACK_Match + ELITE_Match + GENRE_Match + LIT_Match + MAIN_Match + MISC_Match + TRADE_Match + nan_Match + 
                                  P_0_Match + P_1_Match + P_2_Match + P_3_Match + P_4_Match + P_5_Match + P_6_Match + P_7_Match + P_8_Match + P_9_Match + P_10_Match,
                             data = a_1,
                           method="glm",
                           family="poisson",
                           trControl=trainControl(
                             method='cv',number=10
                           ))

```
```{r}            
            summary(log_model1)
```


Model for 1971-1975

```{r, eval=F}
a_2 = amer_novels %>%
      filter(Years=="71-75")

ggplot(a_2, aes(x=connections_books))+geom_density()

    ## BOTH MATCH  version            
            log_model2 = train(connections_books~ BothBlack + BothWhite + BothPOC + BothMale + BothFemale +
                                  BothBlack:BothMale + BothBlack:BothFemale + 
                                  BothWhite:BothMale + BothWhite:BothFemale +
                                  BothPOC:BothMale + BothPOC:BothFemale +
                                  ACAD_Match + BLACK_Match + ELITE_Match + GENRE_Match + LIT_Match + MAIN_Match + MISC_Match + TRADE_Match + nan_Match + 
                                  P_0_Match + P_1_Match + P_2_Match + P_3_Match + P_4_Match + P_5_Match + P_6_Match + P_7_Match + P_8_Match + P_9_Match + P_10_Match,
                             data = a_2,
                           method="glm",
                           family="poisson",
                           trControl=trainControl(
                             method='cv',number=10
                           ))
```
```{r}            
            summary(log_model2)
```


Model for 1976-1980

```{r, eval=F}
a_3 = amer_novels %>%
      filter(Years=="76-80")

ggplot(a_3, aes(x=connections_books))+geom_density()
    ## BOTH MATCH  version            
            log_model3 = train(connections_books~ BothBlack + BothWhite + BothPOC + BothMale + BothFemale +
                                  BothBlack:BothMale + BothBlack:BothFemale + 
                                  BothWhite:BothMale + BothWhite:BothFemale +
                                  BothPOC:BothMale + BothPOC:BothFemale +
                                  ACAD_Match + BLACK_Match + ELITE_Match + GENRE_Match + LIT_Match + MAIN_Match + MISC_Match + TRADE_Match + nan_Match + 
                                  P_0_Match + P_1_Match + P_2_Match + P_3_Match + P_4_Match + P_5_Match + P_6_Match + P_7_Match + P_8_Match + P_9_Match + P_10_Match,
                             data = a_3,
                           method="glm",
                           family="poisson",
                           trControl=trainControl(
                             method='cv',number=10
                           ))
```
```{r}            
            summary(log_model3)
```

Model for 1981-1985

```{r, eval=F}
a_4 = amer_novels %>%
      filter(Years=="81-85")

ggplot(a_4, aes(x=connections_books))+geom_density()  
    ## BOTH MATCH  version            
            log_model4 = train(connections_books~ BothBlack + BothWhite + BothPOC + BothMale + BothFemale +
                                  BothBlack:BothMale + BothBlack:BothFemale + 
                                  BothWhite:BothMale + BothWhite:BothFemale +
                                  BothPOC:BothMale + BothPOC:BothFemale +
                                  ACAD_Match + BLACK_Match + ELITE_Match + GENRE_Match + LIT_Match + MAIN_Match + MISC_Match + TRADE_Match + nan_Match + 
                                  P_0_Match + P_1_Match + P_2_Match + P_3_Match + P_4_Match + P_5_Match + P_6_Match + P_7_Match + P_8_Match + P_9_Match + P_10_Match,
                             data = a_4,
                           method="glm",
                           family="poisson",
                           trControl=trainControl(
                             method='cv',number=10
                           ))
```
```{r}            
            summary(log_model4)
```


Model for 1986-1990

```{r, eval=F}
a_5 = amer_novels %>%
      filter(Years=="86-90")
  
ggplot(a_5, aes(x=connections_books))+geom_density()
    ## BOTH MATCH  version            
            log_model5 = train(connections_books~ BothBlack + BothWhite + BothPOC + BothMale + BothFemale +
                                  BothBlack:BothMale + BothBlack:BothFemale + 
                                  BothWhite:BothMale + BothWhite:BothFemale +
                                  BothPOC:BothMale + BothPOC:BothFemale +
                                  ACAD_Match + BLACK_Match + ELITE_Match + GENRE_Match + LIT_Match + MAIN_Match + MISC_Match + TRADE_Match + nan_Match + 
                                  P_0_Match + P_1_Match + P_2_Match + P_3_Match + P_4_Match + P_5_Match + P_6_Match + P_7_Match + P_8_Match + P_9_Match + P_10_Match,
                             data = a_5,
                           method="glm",
                           family="poisson",
                           trControl=trainControl(
                             method='cv',number=10
                           ))
```
```{r}            
            summary(log_model5)
```

Model for 1991-1995

```{r, eval=F}
a_6 = amer_novels %>%
      filter(Years=="91-95")
  
ggplot(a_6, aes(x=connections_books))+geom_density()
    ## BOTH MATCH  version            
            log_model6 = train(connections_books~ BothBlack + BothWhite + BothPOC + BothMale + BothFemale +
                                  BothBlack:BothMale + BothBlack:BothFemale + 
                                  BothWhite:BothMale + BothWhite:BothFemale +
                                  BothPOC:BothMale + BothPOC:BothFemale +
                                  ACAD_Match + BLACK_Match + ELITE_Match + GENRE_Match + LIT_Match + MAIN_Match + MISC_Match + TRADE_Match + nan_Match + 
                                  P_0_Match + P_1_Match + P_2_Match + P_3_Match + P_4_Match + P_5_Match + P_6_Match + P_7_Match + P_8_Match + P_9_Match + P_10_Match,
                             data = a_6,
                           method="glm",
                           family="poisson",
                           trControl=trainControl(
                             method='cv',number=10
                           ))
```
```{r}            
            summary(log_model6)
```

Model for 1996-2000

```{r, eval=F}
a_7 = amer_novels %>%
      filter(Years=="96-00")
  
ggplot(a_7, aes(x=connections_books))+geom_density()
    ## BOTH MATCH  version            
            log_model7 = train(connections_books~ BothBlack + BothWhite + BothPOC + BothMale + BothFemale +
                                  BothBlack:BothMale + BothBlack:BothFemale + 
                                  BothWhite:BothMale + BothWhite:BothFemale +
                                  BothPOC:BothMale + BothPOC:BothFemale +
                                  ACAD_Match + BLACK_Match + ELITE_Match + GENRE_Match + LIT_Match + MAIN_Match + MISC_Match + TRADE_Match + nan_Match + 
                                  P_0_Match + P_1_Match + P_2_Match + P_3_Match + P_4_Match + P_5_Match + P_6_Match + P_7_Match + P_8_Match + P_9_Match + P_10_Match,
                             data = a_7,
                           method="glm",
                           family="poisson",
                           trControl=trainControl(
                             method='cv',number=10
                           ))
```
```{r}
            summary(log_model7)
```


```{r, eval=F}
# add all model info into one df
model_over_time = 
  bind_rows(cbind(cbind(cbind(Coefficient=rownames(summary(log_model1)$coefficients),data.frame(summary(log_model1)$coefficients)),Years='65-70'),Year=1),
            cbind(cbind(cbind(Coefficient=rownames(summary(log_model2)$coefficients),data.frame(summary(log_model2)$coefficients)),Years='71-75'),Year=2),
            cbind(cbind(cbind(Coefficient=rownames(summary(log_model3)$coefficients),data.frame(summary(log_model3)$coefficients)),Years='76-80'),Year=3),
            cbind(cbind(cbind(Coefficient=rownames(summary(log_model4)$coefficients),data.frame(summary(log_model4)$coefficients)),Years='81-85'),Year=4),
            cbind(cbind(cbind(Coefficient=rownames(summary(log_model5)$coefficients),data.frame(summary(log_model5)$coefficients)),Years='86-90'),Year=5),
            cbind(cbind(cbind(Coefficient=rownames(summary(log_model6)$coefficients),data.frame(summary(log_model6)$coefficients)),Years='91-95'),Year=6),
            cbind(cbind(cbind(Coefficient=rownames(summary(log_model7)$coefficients),data.frame(summary(log_model7)$coefficients)),Years='96-00'),Year=7))

model_over_time$Significance_5 = ifelse(model_over_time$Pr...z..<.05,'*','')
model_over_time$Significance_5_Meaning = ifelse(model_over_time$Pr...z..<.05,'Significant','Not Significant')
model_over_time$Significance_10 = ifelse(model_over_time$Pr...z..<.1,'*','')
model_over_time$Significance_10_Meaning = ifelse(model_over_time$Pr...z..<.1,'Significant','Not Significant')

# create a type column
model_over_time$Type = ifelse(model_over_time$Coefficient=='BothMale'|model_over_time$Coefficient=='BothFemale','Gender',
                            ifelse(model_over_time$Coefficient=='BothBlack'|model_over_time$Coefficient=='BothPOC'|model_over_time$Coefficient=='BothWhite','Race',
                                   ifelse(model_over_time$Coefficient=='(Intercept)','Intercept',
                                                 ifelse(model_over_time$Coefficient=='ACAD_Match'|model_over_time$Coefficient=='BLACK_Match'|
                                                          model_over_time$Coefficient=='ELITE_Match'|model_over_time$Coefficient=='GENRE_Match'|
                                                          model_over_time$Coefficient=='LIT_Match'|model_over_time$Coefficient=='MAIN_Match'|
                                                          model_over_time$Coefficient=='MISC_Match'|model_over_time$Coefficient=='TRADE_Match'|
                                                          model_over_time$Coefficient=='nan_Match','Journal_Type',
                                                        ifelse(model_over_time$Coefficient=='P_0_Match'|model_over_time$Coefficient=='P_1_Match'|
                                                                 model_over_time$Coefficient=='P_2_Match'|model_over_time$Coefficient=='P_3_Match'|
                                                                 model_over_time$Coefficient=='P_4_Match'|model_over_time$Coefficient=='P_5_Match'|
                                                                 model_over_time$Coefficient=='P_6_Match'|model_over_time$Coefficient=='P_7_Match'|
                                                                 model_over_time$Coefficient=='P_8_Match'|model_over_time$Coefficient=='P_9_Match'|
                                                                 model_over_time$Coefficient=='P_10_Match','Publisher','Interaction')))))
```
```{r, echo=F}
ggplot(filter(model_over_time, Type=='Gender'), aes(x=Year, y=Estimate, colour=Coefficient))+
  geom_point()+
  geom_line()+
  geom_text(aes(label=Significance_5, size=3),position=position_dodge(width=0),hjust=1.5, show.legend = F)+
  scale_x_continuous(breaks=model_over_time$Year, labels=model_over_time$Years)+
  theme(legend.position = 'bottom')+
  labs(title='Gender Coefficients, 1950-2000',
       caption='* denotes statistical significance at p=.05',
       x='Years',
       y='Coefficient Estimate')+
  guides(colour=guide_legend(title=NULL))


ggplot(filter(model_over_time, Type=='Race'), aes(x=Year, y=Estimate, colour=Coefficient))+
  geom_point()+
  geom_line()+
  geom_text(aes(label=Significance_5, size=3),position=position_dodge(width=0),hjust=1.5, show.legend = F)+
  scale_x_continuous(breaks=model_over_time$Year, labels=model_over_time$Years)+
  theme(legend.position = 'bottom')+
  labs(title='Race Coefficients, 1950-2000',
       caption='* denotes statistical significance at p=.05',
       x='Years',
       y='Coefficient Estimate')+
  guides(colour=guide_legend(title=NULL))


ggplot(filter(model_over_time, Type=='Journal_Type'), aes(x=Year, y=Estimate, colour=Coefficient))+
  geom_point()+
  geom_line()+
  geom_text(aes(label=Significance_5, size=3),position=position_dodge(width=0),hjust=1.5, show.legend = F)+
  scale_x_continuous(breaks=model_over_time$Year, labels=model_over_time$Years)+
  theme(legend.position = 'bottom')+
  labs(title='Journal Coefficients, 1950-2000',
       caption='* denotes statistical significance at p=.05',
       x='Years',
       y='Coefficient Estimate')+
  guides(colour=guide_legend(title=NULL))

ggplot(filter(model_over_time, Type=='Publisher'), aes(x=Year, y=Estimate, colour=Coefficient))+
  geom_point()+
  geom_line()+
  geom_text(aes(label=Significance_5, size=3),position=position_dodge(width=0),hjust=1.5, show.legend = F)+
  scale_x_continuous(breaks=model_over_time$Year, labels=model_over_time$Years)+
  theme(legend.position = 'bottom')+
  labs(title='Publisher Coefficients, 1950-2000',
       caption='* denotes statistical significance at p=.05',
       x='Years',
       y='Coefficient Estimate')+
  guides(colour=guide_legend(title=NULL))

```

\section{Eigen Regression Analysis}

```{r}
# read in node data
n = read.csv('C:/Users/jyoung22.ADND/Documents/Network Analysis/REVIEWS_1965_2000_NODES_METADATA_EIGENS_2.csv')

# convert levels
n$GENDER = factor(ifelse(n$GENDER==0, 'Male',
                  ifelse(n$GENDER==1, 'Female',NA)),
                  levels=c('Male','Female'))

n$RACE = factor(ifelse(n$RACE==1, 'Black',
                  ifelse(n$RACE==2, 'POC',
                         ifelse(n$RACE==0, 'White',NA))),
                levels=c('White','Black','POC'))

n$P3 = factor(n$P3)

# create Year categories
n$HalfDecades = factor(ifelse(n$YEAR>64 & n$YEAR<71, '65-70',
                       ifelse(n$YEAR>70 & n$YEAR<76, '71-75',
                            ifelse(n$YEAR>75 & n$YEAR<81,'76-80',
                                    ifelse(n$YEAR>80 & n$YEAR<86, '81-85',
                                        ifelse(n$YEAR>85 & n$YEAR<91,'86-90',
                                               ifelse(n$YEAR>90 & n$YEAR<96, '91-95',
                                                    ifelse(n$YEAR>95 | n$YEAR==00,'96-00',NA))))))))

n$Decades = factor(ifelse(n$YEAR<70, '60-69',
                       ifelse(n$YEAR>69 & n$YEAR<80, '70-79',
                            ifelse(n$YEAR>79 & n$YEAR<90,'80-89',
                                    ifelse(n$YEAR>89 & n$YEAR<=99, '90-99',
                                        ifelse(n$YEAR==100 | n$YEAR==00,'00-09',NA))))))

# RandomHouse titles
rh = c("are you there god? it's me, margaret", 'a tidewater morning', 'red square (kandinsky). audio version', "the queen's gambit", 'the war between the tates', 'loon lake', 'the stepford wives', 'steps', "tough guys don't dance", 'good benito', 'brotherly love', "portnoy's complaint", 'footsteps of the hawk', 'creation', 'a month of sundays', 'white shark', 'the run of his life:', 'the december rose', 'civilwarland in bad decline', 'chimera', 'the fermata', 'the palace thief', 'the soloist', ', last notes from home', 'chesapeake', 'indian summer', 'centennial', 'earth', 'confessions of nat turner', 'may you be the mother of a hundred sons', 'the last don', 'when the war is over', 'poland', 'polar star', 'lucky bastard', 'invisible man', 'museums and women and other stories', 'the eagle kite', 'picturing will', 'space', 'family album', 'the male cross-dresser support group', 'turn of the century', "lost man's river", 'ragtime', 'the orchard keeper', 'the theory of everything', 'wanderers eastward, wanderers west', 'woman hollering creek and other stories', 'only children', 'blood meridian', 'the new gothic', 'a son of the circus', 'burr', 'the firm', 'this perfect day', 'the alienist', 'real people', 'music for chameleons', 'the afterlife and other stories (updike). audio version', 'the source', '1876', 'the collected stories of william humphrey', 'me and you', 'werewolves in their youth', 'collected stories of wallace stegner', 'one true thing')

# Major publishers
mp = c('Random House', 'Random Hous', 'Random House audio',
       'Alfred A. Knopf', 'Knopf', 'Knopf Doubleday' ,'Knopf Doubleday Publishing','Knopf,',
       'Ballantine', 'Ballantine Books',
       'Modern Library',
       'Library of America',
       'Pantheon','Pantheon Books')

n$RandomHouse = factor(ifelse(n$TITLE%in%rh,'RH','Other'), levels=c('Other','RH'))
n$MajorPub = factor(ifelse(tolower(trimws(n$PUBLISHER))%in%tolower(mp),'Major','Other'), levels=c('Other','Major'))



ggplot(n, aes(x=EIGEN))+geom_density()
# normal assumption met
```


```{r}
ggplot(na.omit(n), aes(x=YEAR, y=EIGEN, colour=GENDER))+
  facet_wrap(~RACE)+
  geom_smooth()+
  geom_point()+
  labs(main='Eigen Scores by Race and Gender',
       caption='LOESS smoothing used',
       x='Year',
       y='Eigen Score',
       colour='Gender')

ggplot(na.omit(n), aes(x=YEAR, y=EIGEN, colour=MajorPub))+
#  facet_wrap(~GENDER)+
  geom_smooth()+
  geom_point()+
  labs(main='Eigen Scores by Publisher',
       caption='GAM smoothing used',
       x='Year',
       y='Eigen Score',
       colour='Major Publisher')

ggplot(na.omit(n), aes(x=YEAR, y=EIGEN, colour=MajorPub))+
  facet_wrap(~GENDER)+
  geom_smooth()+
  geom_point()+
  labs(main='Eigen Scores by Publisher',
       caption='LOESS smoothing used',
       x='Year',
       y='Eigen Score',
       colour='Major Publisher')
```


```{r}
# Major Pub only
n_model = train(EIGEN~ GENDER + RACE  + HalfDecades + MajorPub + # main effects
                  RACE:GENDER + RACE:HalfDecades + RACE:MajorPub + GENDER:HalfDecades + GENDER:MajorPub + HalfDecades:MajorPub + # first interactions
                  GENDER:RACE:HalfDecades + GENDER:RACE:MajorPub,# + GENDER:HalfDecades:MajorPub + RACE:HalfDecades:MajorPub, + # 2nd level interactions, 2 NS
                  #GENDER:RACE:HalfDecades:MajorPub, # 3rd level interactions # not significant
                   data = na.omit(n),
                   method="glm",
                   family="gaussian",
                   trControl=trainControl(
                     method='cv',number=10
                   ))

            summary(n_model)
            n_model            

            varImp(n_model)
            
            plot(y=n_model$finalModel$residuals, x=n_model$finalModel$fitted.values, ylab='Residuals', main='Residual Plot') # resid
            qqnorm(n_model$finalModel$residuals)# qq
            
            regplot(n_model, cex.axis = .5)
```
```{r,eval=F}
# Random House only            
n1_model = train(EIGEN~ GENDER + RACE  + HalfDecades + RandomHouse + # main effects
                  RACE:GENDER + RACE:HalfDecades + RACE:RandomHouse + GENDER:HalfDecades + GENDER:RandomHouse + HalfDecades:RandomHouse + # first interactions
                  GENDER:RACE:HalfDecades + GENDER:RACE:RandomHouse,# + GENDER:HalfDecades:RandomHouse + RACE:HalfDecades:RandomHouse + # 2nd level interactions, 2 NS
                  #GENDER:RACE:HalfDecades:RandomHouse, # 3rd level interactions # not significant
                   data = na.omit(n),
                   method="glm",
                   family="gaussian",
                   trControl=trainControl(
                     method='cv',number=10
                   ))

            summary(n1_model)
            n1_model            

            varImp(n1_model)
            
            plot(y=n1_model$finalModel$residuals, x=n1_model$finalModel$fitted.values, ylab='Residuals', main='Residual Plot') # resid

            qqnorm(n1_model$finalModel$residuals)# qq

            
# P3 only
n3_model = train(EIGEN~ GENDER + RACE  + HalfDecades + P3 + # main effects
                  RACE:GENDER + RACE:HalfDecades + RACE:P3 + GENDER:HalfDecades + GENDER:P3 + HalfDecades:P3,# + # first interactions
                  #GENDER:RACE:HalfDecades + GENDER:RACE:P3,# + GENDER:HalfDecades:P3,# + RACE:HalfDecades:P3,# +  2nd level interactions, 2 NS
                  #GENDER:RACE:HalfDecades:P3, # 3rd level interactions # not significant
                   data = na.omit(n),
                   method="glm",
                   family="gaussian",
                   trControl=trainControl(
                     method='cv',number=10
                   ))

            summary(n3_model)
            n3_model            

            varImp(n3_model)
            
            plot(y=n3_model$finalModel$residuals, x=n3_model$finalModel$fitted.values, ylab='Residuals', main='Residual Plot') # resid
            qqnorm(n3_model$finalModel$residuals)# qq            
```


The above varImp function automatically scales the variable importance out of 100 to make it easier to interpret.

